import type { Catalog } from "./types";

const NOW = Date.UTC(2026, 6, 11);

export const SEED: Catalog = {
  updatedAt: NOW,
  categories: [
    {
      id: "c-work",
      slug: "desk-work",
      name: "デスク・充電",
      emoji: "⌨️",
      zone: "river",
      intro: "配線、充電切れ、持ち運びの小さな手間を減らす道具を、仕様の見方から整理します。",
      problem: "机まわりの探し物と充電待ちを減らしたい",
      accent: "#315c4f",
    },
    {
      id: "c-home",
      slug: "home-storage",
      name: "収納・片づけ",
      emoji: "🧺",
      zone: "pond",
      intro: "片づけを頑張るのではなく、戻しやすい仕組みに変えるための道具を選びます。",
      problem: "出しっぱなしと探し物を減らしたい",
      accent: "#9a5b3f",
    },
    {
      id: "c-carry",
      slug: "daily-carry",
      name: "持ち歩き",
      emoji: "☂️",
      zone: "sea",
      intro: "忘れ物や急な天候で予定を崩さない、軽くて常備しやすい道具を比較します。",
      problem: "外出先の小さな困りごとを先回りしたい",
      accent: "#455c79",
    },
    {
      id: "c-learn",
      slug: "learning-tools",
      name: "学び・仕事術",
      emoji: "📚",
      zone: "pond",
      intro: "情報を集めるだけで終わらず、すぐ試せる形に変える本やツールを扱います。",
      problem: "学んだことを仕事で使える形にしたい",
      accent: "#765b8d",
    },
  ],
  products: [
    {
      id: "p-usbc-100w",
      slug: "usb-c-100w-cable",
      categoryId: "c-work",
      title: "USB-C 100W対応ケーブルの選び方",
      shortTitle: "USB-C 100Wケーブル",
      emoji: "🔌",
      price: "参考価格帯 ¥1,000〜¥2,000",
      priceMin: 1000,
      priceMax: 2000,
      note: "スマホとノートPCの充電ケーブルを1本にまとめたい人向け。100W表記だけでなく、E-Markerとデータ転送規格も確認します。",
      url: "https://www.amazon.co.jp/s?k=USB-C+100W+E-Marker+%E3%82%B1%E3%83%BC%E3%83%96%E3%83%AB",
      problem: "端末ごとにケーブルを持ち替える手間と、充電が遅いストレスを減らす。",
      verdict: "充電目的なら、100W以上・E-Marker搭載・1m前後を基準にすると選びやすいです。映像出力や高速データ転送も必要なら、USB 3.2またはUSB4の表記を別途確認してください。",
      bestFor: ["スマホとUSB-CノートPCを1本で充電したい", "出張や通勤の荷物を減らしたい", "充電器はすでに65W以上を使っている"],
      notFor: ["映像出力を必須にしているが規格を確認したくない", "Lightning端子の機器が中心", "長さ3m以上を最優先したい"],
      checklist: ["100W以上の給電表記", "E-Marker搭載の明記", "必要ならUSB 3.2／USB4対応", "端子根元の補強と保証期間"],
      pros: ["対応端末なら充電ケーブルを共通化できる", "1m前後は机でも持ち歩きでも扱いやすい", "ナイロン被覆は擦れへの安心感がある"],
      cautions: ["100W表記だけでは高速データ転送や映像出力を保証しない", "充電器側の出力が低ければ速度は上がらない", "太いケーブルは取り回しが悪い場合がある"],
      keywords: ["USB-C 100W ケーブル 選び方", "E-Marker 必要", "ノートPC 充電ケーブル 共用"],
      clicks: 0,
      ts: NOW,
      updatedAt: NOW,
      pinned: true,
    },
    {
      id: "p-folding-storage",
      slug: "folding-storage-box",
      categoryId: "c-home",
      title: "折りたたみ収納ボックスの選び方",
      shortTitle: "折りたたみ収納ボックス",
      emoji: "🧺",
      price: "参考価格帯 ¥2,000〜¥4,000",
      priceMin: 2000,
      priceMax: 4000,
      note: "季節用品や防災備蓄をまとめ、使わない時は薄くしまえる収納。容量より先に置き場所と開き方を決めます。",
      url: "https://www.amazon.co.jp/s?k=%E6%8A%98%E3%82%8A%E3%81%9F%E3%81%9F%E3%81%BF+%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9+%E3%83%95%E3%82%BF%E4%BB%98%E3%81%8D",
      problem: "中身が見えない箱を積み重ね、必要な物を探し直す手間を減らす。",
      verdict: "先に収納場所の内寸を測り、正面からも開けられるタイプを選ぶと、積んだまま出し入れできます。衣類中心なら通気性、防災備蓄なら耐荷重とロックを優先してください。",
      bestFor: ["季節家電や衣類をまとめたい", "引っ越しや模様替えが多い", "積み重ねたまま中身を取り出したい"],
      notFor: ["湿気の多い場所で完全密閉したい", "重い書籍を大量に収納したい", "置き場所の寸法を測れない"],
      checklist: ["設置場所の幅・奥行き・高さ", "正面扉の有無と開閉スペース", "積載・耐荷重の表記", "キャスターまたは持ち手の必要性"],
      pros: ["空の時に薄くできる", "同じ規格で揃えると空間を使いやすい", "正面開きなら積み替えが減る"],
      cautions: ["大容量ほど入れすぎて重くなりやすい", "柔らかい素材は積み重ねに向かない", "密閉性が高い場合は湿気対策が必要"],
      keywords: ["折りたたみ収納ボックス 選び方", "収納ボックス 正面開き", "季節家電 収納"],
      clicks: 0,
      ts: NOW,
      updatedAt: NOW,
    },
    {
      id: "p-light-umbrella",
      slug: "lightweight-folding-umbrella",
      categoryId: "c-carry",
      title: "軽量折りたたみ傘の選び方",
      shortTitle: "軽量折りたたみ傘",
      emoji: "☂️",
      price: "参考価格帯 ¥2,500〜¥5,000",
      priceMin: 2500,
      priceMax: 5000,
      note: "常備しやすさと雨への強さのバランスが重要。重さだけでなく、親骨の長さと収納時サイズを見ます。",
      url: "https://www.amazon.co.jp/s?k=%E6%8A%98%E3%82%8A%E3%81%9F%E3%81%9F%E3%81%BF%E5%82%98+%E8%BB%BD%E9%87%8F+200g+%E6%92%A5%E6%B0%B4",
      problem: "天気予報を見て傘を出し入れする手間と、急な雨で買い直す出費を減らす。",
      verdict: "常時携帯なら200〜250g前後、親骨50〜55cmを基準にすると、軽さと実用性のバランスを取りやすいです。風の強い地域では軽さより骨の構造を優先してください。",
      bestFor: ["通勤バッグに傘を入れっぱなしにしたい", "急な雨のたびにビニール傘を買っている", "軽さと最低限の覆う広さを両立したい"],
      notFor: ["強風下での使用が多い", "大柄で肩や荷物まで広く覆いたい", "自動開閉を最優先する"],
      checklist: ["本体重量200〜250g前後", "親骨50〜55cm以上", "収納時の全長と太さ", "撥水等級や生地の仕様", "修理・保証の有無"],
      pros: ["毎日持ち歩きやすい", "突然の雨への買い直しを減らせる", "晴雨兼用なら持ち物を一本化できる"],
      cautions: ["超軽量モデルは面積や耐風性を抑えていることがある", "ケースが細すぎると濡れた後に戻しにくい", "撥水性能は使用とともに低下する"],
      keywords: ["折りたたみ傘 軽量 選び方", "折りたたみ傘 200g", "通勤 傘 入れっぱなし"],
      clicks: 0,
      ts: NOW,
      updatedAt: NOW,
      pinned: true,
    },
    {
      id: "p-ai-prompt-book",
      slug: "ai-prompt-book-guide",
      categoryId: "c-learn",
      title: "生成AIの入門書を選ぶ基準",
      shortTitle: "生成AIの入門書",
      emoji: "📖",
      price: "参考価格帯 ¥1,500〜¥3,000",
      priceMin: 1500,
      priceMax: 3000,
      note: "プロンプト例の量より、課題分解・検証・情報管理まで説明しているかで選びます。",
      url: "https://www.amazon.co.jp/s?k=%E7%94%9F%E6%88%90AI+%E5%85%A5%E9%96%80+%E6%9C%AC+%E3%83%97%E3%83%AD%E3%83%B3%E3%83%97%E3%83%88",
      problem: "例文をコピーして終わり、別の業務に応用できない状態を抜ける。",
      verdict: "特定サービスの画面操作だけでなく、目的の分解、入力情報の整理、出力の検証、機密情報の扱いまで含む本を選ぶと、サービスが変わっても知識を転用しやすくなります。",
      bestFor: ["生成AIを仕事で使い始めたい", "プロンプト集を試したが応用できなかった", "出力の確認方法まで学びたい"],
      notFor: ["最新ツールの機能一覧だけを探している", "特定資格の試験対策が目的", "プログラミング実装だけを深掘りしたい"],
      checklist: ["発行日と改訂情報", "課題分解の説明", "出力検証・ファクトチェックの章", "著作権・機密情報の扱い", "具体例と汎用原則のバランス"],
      pros: ["体系立てて学べる", "手元で振り返りやすい", "サービス固有でない原則は長く使える"],
      cautions: ["画面仕様やモデル名は短期間で変わる", "例文の多さだけでは応用力につながらない", "業務利用では組織のルール確認が必要"],
      keywords: ["生成AI 入門書 おすすめ 基準", "プロンプト 本 選び方", "生成AI 仕事 活用 本"],
      clicks: 0,
      ts: NOW,
      updatedAt: NOW,
    },
  ],
};

export function getCategory(categoryId: string) {
  return SEED.categories.find((category) => category.id === categoryId);
}

export function getCategoryBySlug(slug: string) {
  return SEED.categories.find((category) => category.slug === slug);
}

export function getProductBySlug(slug: string) {
  return SEED.products.find((product) => product.slug === slug);
}
